### ISSUE TITLE
Document Azure Active Directory

### ISSUE THREAD

**Issue by pratapvardhan** [gramexrecipes/gramex-guide#4]
Add `access_token > body > resource: https://graph.microsoft.com/`

```yaml
  auth/aad:
    pattern: /$YAMLURL/login
    handler: OAuth2
    kwargs:
      client_id: '1239bdca-----------------------------'
      client_secret: 'Pyum-----------------------------'
      authorize:
        url: 'https://login.microsoftonline.com/{TENANT_ID}/oauth2/authorize'
      access_token:
        url: 'https://login.microsoftonline.com/{TENANT_ID}/oauth2/token'
        body:
          grant_type: 'authorization_code'
          resource: https://graph.microsoft.com/
      user_info:
        url: 'https://graph.microsoft.com/v1.0/me/'
        headers:
          Authorization: 'Bearer {access_token}'
          Accept: 'application/json'
          Content-Type: 'application/json'
```
